dist: xenial
sudo: required

language: c

addons:
  apt:
    packages:
      - automake
      - make
      - automake
      - libtool
      - pkg-config
      - gcc
      - cproto
      - g++
      - git-core
      - luajit
      - libluajit-5.1-dev
      - lua-unit
      - uthash-dev

install:
  - cd ../../
  - git clone git://github.com/kmarkus/uutils
  - git clone git://github.com/liblfds/liblfds6.1.1
  # install uutils
  - cd uutils/
  - sudo make install
  - cd ..
  # install liblfds
  - cd liblfds6.1.1
  - git -c user.name='travis' -c user.email='xxx' am ../kmarkus/microblx/liblfds/*.patch
  - ./bootstrap
  - ./configure --prefix=/usr/
  - make
  - sudo make install
  - cd ..
    
script:
  - cd kmarkus/microblx
  - ./bootstrap
  - ./configure --prefix=/usr/
  - make
  - sudo make install
  # - ./run_tests.sh
  
