dist: xenial
sudo: required

language: c

addons:
  apt:
    packages:
      - automake
      - make
      - automake
      - libtool
      - pkg-config
      - gcc
      - cproto
      - g++
      - git-core
      - luajit
      - libluajit-5.1-dev
      - uthash-dev
      - cppcheck

install:
  - cd ../../
  - git clone --depth=1 git://github.com/kmarkus/uutils
  - git clone --depth=1 git://github.com/liblfds/liblfds6.1.1
  - git clone --depth=1 -b LUAUNIT_V3_3 git://github.com/bluebird75/luaunit
  # install uutils
  - cd uutils/
  - sudo make install
  - cd ..
  # install luaunit
  - sudo install -Dt /usr/share/lua/5.1/ luaunit/luaunit.lua
  # install liblfds
  - cd liblfds6.1.1
  - git -c user.name='travis' -c user.email='xxx' am ../kmarkus/microblx/liblfds/*.patch
  - ./bootstrap
  - ./configure --prefix=/usr/
  - make -j3
  - sudo make install
  - cd ..
    
script:
  - cd kmarkus/microblx
  - ./bootstrap
  - ./configure --prefix=/usr/
  - make cppcheck
  - make -j3
  - sudo make install
  - ./run_tests.sh
  # test generating an out-of-tree block
  - ubx-genblock -d /tmp/testblock/ -c examples/blockmodels/block_model_example.lua
  - cd /tmp/testblock/
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - ubx-launch -t 1 -webif -c myblock.usc
  - cd /usr/share/ubx/examples/usc/pid/
  - ubx-launch -t 3 -s -check unconn_inports,unconn_outports -c pid_test.usc,ptrig_nrt.usc